on:
    workflow_call:
        inputs:
            issue_number:
                description: The issue number
                required: true
                type: string

jobs:
    comment-and-close:
        runs-on: ubuntu-latest
        steps:
            - run: |
                gh issue close ${{ inputs.issue_number }} -R ${{ github.repository }} --comment 'If you would like to file a bug report or feature request, please refer to our issue tracker: https://dhis2.atlassian.net'
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
