on:
    workflow_call:

jobs:
    lint-pr-title:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: yarn
            - run: yarn install --frozen-lockfile
            - id: commitlint
              run: echo ::set-output name=config_path::$(node -e "process.stdout.write(require('@dhis2/cli-style').config.commitlint)")
            - run: echo "${{ github.event.pull_request.title }}" | npx commitlint --config ${{ steps.commitlint.outputs.config_path }}
