on:
    workflow_call:
        inputs:
            publish_apphub:
                description: Whether to publish to apphub
                default: true
                required: false
                type: boolean
            publish_github:
                description: Whether to publish to github
                default: true
                required: false
                type: boolean
            skip_deploy_build:
                description: Whether to publish to D2 artifacts
                default: false
                required: false
                type: boolean
        secrets:
            DHIS2_BOT_GITHUB_TOKEN:
                required: true
            DHIS2_BOT_APPHUB_TOKEN:
                required: true

env:
    GIT_AUTHOR_NAME: '@dhis2-bot'
    GIT_AUTHOR_EMAIL: apps@dhis2.org
    GIT_COMMITTER_NAME: '@dhis2-bot'
    GIT_COMMITTER_EMAIL: apps@dhis2.org

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  token: ${{ secrets.DHIS2_BOT_GITHUB_TOKEN }}
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: yarn
            - run: yarn install --frozen-lockfile
            - run: yarn d2-app-scripts build
            - uses: dhis2/action-semantic-release@master
              with:
                  publish-apphub: ${{ inputs.publish_apphub }}
                  publish-github: ${{ inputs.publish_github }}
                  github-token: ${{ secrets.DHIS2_BOT_GITHUB_TOKEN }}
                  apphub-token: ${{ secrets.DHIS2_BOT_APPHUB_TOKEN }}
            - uses: dhis2/deploy-build@master
              if: ${{ inputs.skip_deploy_build == false }}
              with:
                  build-dir: build/app
                  github-token: ${{ secrets.DHIS2_BOT_GITHUB_TOKEN }}
